apps/df_cart/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = 'df_cart'

urlpatterns = [
    url(r'^$', views.user_cart, name="cart"),
    url(r'^add(\d+)_(\d+)/$', views.add, name="add"),
    url(r'^edit(\d+)_(\d+)/$', views.edit, name="edit"),
    url(r'^delete(\d+)/$', views.delete, name="delete"),
]

apps/df_goods/urls.py
from django.conf.urls import url

from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.good_list, name="good_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
]

apps/df_user/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

app_name = 'df_user'

urlpatterns = [
    url(r'^register/$', register, name="register"),
    url(r'^register_handle/$', register_handle, name="register_handle"),
    url(r'^register_exist/$', register_exist, name="register_exist"),
    url(r'^login/$', login, name="login"),
    url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^info/$', info, name="info"),
    url(r'^order/(\d+)$', order, name="order"),
    url(r'^site/$', site, name="site"),
    # url(r'^place_order/$', views.place_order),
    url(r'^logout/$', logout, name="logout"),
]

demo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve  # 上传文件处理函数

from .settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls')),  # 使用富文本编辑框配置confurl
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT})
]

templates/base.html
{% extends 'base_foot.html' %}

{% block body %}

    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
{#                判断是否已经登录#}
                {% if request.session.user_name|default:'' != '' %}
{#                    default过滤器进行判断如果request.session.user_name不等于空字符串则用户登陆状态为true#}
{#                    也就是说当用户为已登陆状态时则显示用户名#}

{#                    class="login_info fl"#}
				<div class="login_btn fl">欢迎您：<em>{{ request.session.user_name }}</em>
                    <span>|</span>
                    <em><a href="{% url "df_user:logout" %}">退出</a></em>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url "df_user:login" %}">登录</a>
					<span>|</span>
					<a href="{% url "df_user:register" %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url "df_user:info" %}">用户中心</a>
					<span>|</span>
					<a href="{% url "df_cart:cart" %}">我的购物车</a>
					<span>|</span>
					<a href="{% url "df_user:order" 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>


    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
        {% if page_name == 1 %}
            <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
        {% endif %}
		<div class="search_con fl">
             <script>
                $(function () {
                    $('.input_btn').click(function () {
                        q = $('.input_text').val();
                        if(q==""){
                        alert("请输入搜索内容");
                        }
                        else{
                            location.href = '{% url "df_goods:ordinary_search" %}?q='+q+'&page=1'
                        }
                    })
                })

            </script>
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>

        {% if guest_cart == 1 %}
            <div class="guest_cart fr">
                <a href="{% url "df_cart:cart" %}" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">{{ cart_num }}</div>
            </div>
        {% endif %}
	</div>




{% block content %}
{% endblock content %}
{% block center_body %}

{% endblock center_body %}


{% endblock body %}

templates/base_foot.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{{ title }} | 天天生鲜</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{#	<script type="text/javascript" src="/static/js/register.js"></script>#}
    {% block head %}{% endblock head %}
</head>
<body>

{% block body %}{% endblock body %}

    <div class="footer no-mp">
		<div class="foot_link">
			<a href="https://github.com/weilanhanf/daily_fresh_demo">关于我们</a>
			<span>|</span>
			<a href="https://www.cnblogs.com/welan/">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2018 大佬说的都队 All Rights Reserved</p>
		<p>电话：***-*******    京ICP备********号</p>
	</div>

</body>
</html>